using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Transcom.Models
{
    public class TextTracksResponse
    {
        public List<TextTracksValue> value { get; set; }
    }
    public class TextTracksValue
    {
        public string id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string language { get; set; }
        public string url { get; set; }
        public bool autoGenerated { get; set; }
    }
}
